### ISSUE TITLE
Got my account flagged for phone verication 

### ISSUE THREAD

**Issue by arnavgpt** [adversarialtools/discord-delete#54]
Yesterday, when I was using this tool, I got my account flagged for phone verification.

I would request you to either implement a functioning rate limiter or use a library that has rate limiting functionality.
You could also add a parameter for request delay(as described in #40)

**Comment by cedws** [comment]
Thanks. I can put something in the README but I'm afraid this is WONTFIX. Even with the rate limited, it's impossible to know what rate triggers phone verification. There's probably other things that trigger it too.

**Comment by cedws** [comment]
Note added to README.
